//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 7/19/2019 12:25:55 PM
namespace XamarinForms3DCarSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/XamarinForms3DCarSample.wgame </summary>
        public const string GameInfo = "Content/XamarinForms3DCarSample.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/SDM100.fbx </summary>
            public const string SDM100_fbx = "Content/Assets/SDM100.fbx";
            
            /// <summary> Path to Content/Assets/SDM_100.wpref </summary>
            public const string SDM_100 = "Content/Assets/SDM_100.wpref";
            
            public sealed class SDM_500_Textures
            {
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/Exterior_SDM_500.png </summary>
                public const string Exterior_SDM_500_png = "Content/Assets/SDM_500_Textures/Exterior_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/details_SDM_500.png </summary>
                public const string details_SDM_500_png = "Content/Assets/SDM_500_Textures/details_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/Tickets_SDM_500.png </summary>
                public const string Tickets_SDM_500_png = "Content/Assets/SDM_500_Textures/Tickets_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/interior_SDM_500.png </summary>
                public const string interior_SDM_500_png = "Content/Assets/SDM_500_Textures/interior_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/arrow_SDM_500.png </summary>
                public const string arrow_SDM_500_png = "Content/Assets/SDM_500_Textures/arrow_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/shadow_SDM_500.png </summary>
                public const string shadow_SDM_500_png = "Content/Assets/SDM_500_Textures/shadow_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/desglose_SDM_500.png </summary>
                public const string desglose_SDM_500_png = "Content/Assets/SDM_500_Textures/desglose_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/Pantalles_SDM_500.png </summary>
                public const string Pantalles_SDM_500_png = "Content/Assets/SDM_500_Textures/Pantalles_SDM_500.png";
                
                /// <summary> Path to Content/Assets/SDM_500_Textures/billetes_SDM_500.png </summary>
                public const string billetes_SDM_500_png = "Content/Assets/SDM_500_Textures/billetes_SDM_500.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/CDS_508.fbx </summary>
                public const string CDS_508_fbx = "Content/Assets/Materials/CDS_508.fbx";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #3.wmat </summary>
                public const string Material_243_Slot_3 = "Content/Assets/Materials/Material #243 Slot #3.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2704.wmat </summary>
                public const string Material_2704 = "Content/Assets/Materials/Material #2704.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1692.wmat </summary>
                public const string Material_1692 = "Content/Assets/Materials/Material #1692.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1671.wmat </summary>
                public const string Material_1671 = "Content/Assets/Materials/Material #1671.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1670.wmat </summary>
                public const string Material_1670 = "Content/Assets/Materials/Material #1670.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2709.wmat </summary>
                public const string Material_2709 = "Content/Assets/Materials/Material #2709.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #349.wmat </summary>
                public const string Material_349 = "Content/Assets/Materials/Material #349.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #543.wmat </summary>
                public const string Material_543 = "Content/Assets/Materials/Material #543.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2705.wmat </summary>
                public const string Material_2705 = "Content/Assets/Materials/Material #2705.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #2.wmat </summary>
                public const string Material_243_Slot_2 = "Content/Assets/Materials/Material #243 Slot #2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2713.wmat </summary>
                public const string Material_2713 = "Content/Assets/Materials/Material #2713.wmat";
                
                /// <summary> Path to Content/Assets/Materials/09 - Defaultsdf.wmat </summary>
                public const string _09_Defaultsdf = "Content/Assets/Materials/09 - Defaultsdf.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2714.wmat </summary>
                public const string Material_2714 = "Content/Assets/Materials/Material #2714.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #5.wmat </summary>
                public const string Material_243_Slot_5 = "Content/Assets/Materials/Material #243 Slot #5.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1695.wmat </summary>
                public const string Material_1695 = "Content/Assets/Materials/Material #1695.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #4.wmat </summary>
                public const string Material_243_Slot_4 = "Content/Assets/Materials/Material #243 Slot #4.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #343.wmat </summary>
                public const string Material_343 = "Content/Assets/Materials/Material #343.wmat";
                
                /// <summary> Path to Content/Assets/Materials/24 - Default.wmat </summary>
                public const string _24_Default = "Content/Assets/Materials/24 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/02 - Default.wmat </summary>
                public const string _02_Default = "Content/Assets/Materials/02 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1696.wmat </summary>
                public const string Material_1696 = "Content/Assets/Materials/Material #1696.wmat";
                
                /// <summary> Path to Content/Assets/Materials/White Plane.wmat </summary>
                public const string White_Plane = "Content/Assets/Materials/White Plane.wmat";
                
                /// <summary> Path to Content/Assets/Materials/cristal.wmat </summary>
                public const string cristal = "Content/Assets/Materials/cristal.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #356.wmat </summary>
                public const string Material_356 = "Content/Assets/Materials/Material #356.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #6.wmat </summary>
                public const string Material_243_Slot_6 = "Content/Assets/Materials/Material #243 Slot #6.wmat";
                
                /// <summary> Path to Content/Assets/Materials/03 - Default.wmat </summary>
                public const string _03_Default = "Content/Assets/Materials/03 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1697.wmat </summary>
                public const string Material_1697 = "Content/Assets/Materials/Material #1697.wmat";
                
                /// <summary> Path to Content/Assets/Materials/DefaultMaterial.wmat </summary>
                public const string DefaultMaterial = "Content/Assets/Materials/DefaultMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/11 - Default.wmat </summary>
                public const string _11_Default = "Content/Assets/Materials/11 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1674.wmat </summary>
                public const string Material_1674 = "Content/Assets/Materials/Material #1674.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2706.wmat </summary>
                public const string Material_2706 = "Content/Assets/Materials/Material #2706.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #243 Slot #1.wmat </summary>
                public const string Material_243_Slot_1 = "Content/Assets/Materials/Material #243 Slot #1.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #346.wmat </summary>
                public const string Material_346 = "Content/Assets/Materials/Material #346.wmat";
                
                /// <summary> Path to Content/Assets/Materials/13 - Default.wmat </summary>
                public const string _13_Default = "Content/Assets/Materials/13 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2710.wmat </summary>
                public const string Material_2710 = "Content/Assets/Materials/Material #2710.wmat";
                
                /// <summary> Path to Content/Assets/Materials/09 - Default.wmat </summary>
                public const string _09_Default = "Content/Assets/Materials/09 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1673.wmat </summary>
                public const string Material_1673 = "Content/Assets/Materials/Material #1673.wmat";
                
                /// <summary> Path to Content/Assets/Materials/01 - Default.wmat </summary>
                public const string _01_Default = "Content/Assets/Materials/01 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1672.wmat </summary>
                public const string Material_1672 = "Content/Assets/Materials/Material #1672.wmat";
            }
            
            public sealed class CDS_508_Textures
            {
                
                /// <summary> Path to Content/Assets/CDS_508_Textures/internal_508.png </summary>
                public const string internal_508_png = "Content/Assets/CDS_508_Textures/internal_508.png";
                
                /// <summary> Path to Content/Assets/CDS_508_Textures/monedas_508.jpg </summary>
                public const string monedas_508_jpg = "Content/Assets/CDS_508_Textures/monedas_508.jpg";
                
                /// <summary> Path to Content/Assets/CDS_508_Textures/TICKETS_508.png </summary>
                public const string TICKETS_508_png = "Content/Assets/CDS_508_Textures/TICKETS_508.png";
                
                /// <summary> Path to Content/Assets/CDS_508_Textures/Collapsed_508.png </summary>
                public const string Collapsed_508_png = "Content/Assets/CDS_508_Textures/Collapsed_508.png";
                
                /// <summary> Path to Content/Assets/CDS_508_Textures/Cartelas_508.png </summary>
                public const string Cartelas_508_png = "Content/Assets/CDS_508_Textures/Cartelas_508.png";
            }
            
            public sealed class CDS_801_Textures
            {
                
                /// <summary> Path to Content/Assets/CDS_801_Textures/Bag_801.png </summary>
                public const string Bag_801_png = "Content/Assets/CDS_801_Textures/Bag_801.png";
                
                /// <summary> Path to Content/Assets/CDS_801_Textures/All_801.png </summary>
                public const string All_801_png = "Content/Assets/CDS_801_Textures/All_801.png";
                
                /// <summary> Path to Content/Assets/CDS_801_Textures/Details_801.png </summary>
                public const string Details_801_png = "Content/Assets/CDS_801_Textures/Details_801.png";
            }
            
            public sealed class SDM_100_Textures
            {
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/interior_merge_SDM_100.png </summary>
                public const string interior_merge_SDM_100_png = "Content/Assets/SDM_100_Textures/interior_merge_SDM_100.png";
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/SMD_Details_100.png </summary>
                public const string SMD_Details_100_png = "Content/Assets/SDM_100_Textures/SMD_Details_100.png";
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/All_tickets_SDM_100.png </summary>
                public const string All_tickets_SDM_100_png = "Content/Assets/SDM_100_Textures/All_tickets_SDM_100.png";
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/SDM_100.png </summary>
                public const string SDM_100_png = "Content/Assets/SDM_100_Textures/SDM_100.png";
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/Pantallas_SDM_100.png </summary>
                public const string Pantallas_SDM_100_png = "Content/Assets/SDM_100_Textures/Pantallas_SDM_100.png";
                
                /// <summary> Path to Content/Assets/SDM_100_Textures/xifres entrada_SDM_100.png </summary>
                public const string xifres_entrada_SDM_100_png = "Content/Assets/SDM_100_Textures/xifres entrada_SDM_100.png";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Loading.wscene </summary>
            public const string Loading = "Content/Scenes/Loading.wscene";
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
